version: 2
updates:
  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: gradle
    directory: /services/connexa-api
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
